### PR TITLE
feat: w3console example app

### PR DESCRIPTION
**Pull request by travis**
Introduce w3console, a demonstration of the "Customizable" components introduced in #208 and the start of a new console for interacting with w3up. 

Screen Shot 2023-01-13 at 12 27 14 PM

w3console is built primarily with Customizable components and is a demonstration of how those components can be customized with a mix of CSS variables and popular tools like TailwindCSS.

Using the Customizable components in this app drove a few important bugfixes and improvements in those components, so I'm setting this PR to merge into that PR for now - I think it may make sense to bundle this together with those changes in general. We need to keep iterating on the visual design, but that doesn't necessarily need to happen before merge.

https://github.com/web3-storage/w3ui/pull/255/files#diff-e018ff5c0db64a5ab5309ee989a3e1506b6a715f75e6d1c59bf0dbfe4c068296 is now a great example of how the customizable components can be used - not much code, lots of functionality

https://github.com/web3-storage/w3ui/pull/255/files#diff-e103e84df17b851f230d8a61eb981470f2d4b67047c4686d083c3bfe1195ee61 shows how we can use CSS variables and TailwindCSS to customize these components

### CODE REVIEW

**Comment by travis** [comment]
this PR originally had a bunch of changes to the customizable components, but I decided to move them to the upstream PR: 

https://github.com/web3-storage/w3ui/pull/208/commits/3faa2bcb1025340d3eb95b04ebd8a868bf9ab85b

**Comment by olizilla** [comment]
Rad!

you probably got this figured out already but note that the `SimpleAuthenticator` adds `flex` in the css for `w3ui-simple-authenticator` which is why the ui isn't taking up the available screen space yet, the immediate child component needs to provide a width and height.

**Comment by olizilla** [comment]
I've updated this PR to deal with the renames in #208 and edited the layout to move closer to one of the wireframes shared by @jchris as an exploration that seemed helpful.

**WIP Preview**
Screenshot 2023-01-17 at 12 24 39

**Wireframe**
Screen Shot 2022-11-11 at 9 57 43 AM

**Comment by travis** [comment]
chatted with @olizilla this morning - he's reviewed my changes and I've reviewed his, so merging this to make coordination and planning easier - it's a self-contained example so pretty low risk.

**Pull request merged**
