### PR TITLE
feat: add warnings about the public and permanent nature of w3up uploads

### LINKED ISSUE #464: Warnings about public and permanent data
we should leave these warnings in our deployed w3consoles. These are on the NFT.Storage and web3.storage web apps and docs, and still apply here.

> ⚠️❗ __Public Data__ 🌎: All data uploaded to w3up is available to anyone who requests it using the correct CID. Do not store any private or sensitive information in an unencrypted form using w3up.

> ⚠️❗ __Permanent Data__ ♾️: Removing files from w3up will remove them from the file listing for your account, but that doesn’t prevent nodes on the decentralized storage network from retaining copies of the data indefinitely. Do not use w3up for data that may need to be permanently deleted in the future.

### PR DESCRIPTION
**Pull request by travis**
we'll probably want to rework this in the future, but I think this probably looks good enough for now:

Screenshot 2023-04-07 at 1 47 15 PM
Screenshot 2023-04-07 at 1 47 29 PM
resolves #464

### CODE REVIEW

**Comment by dchoi27** [comment]
thanks! wdyt about making the warnings right justified instead of left?

**Comment by travis** [comment]
works for me! will update

**Comment by travis** [comment]
> could also consider putting the warnings outside the dotted line?

I like this even more! I think in this case we should just keep it below the upload box in both cases:

Screenshot 2023-04-07 at 1 47 15 PM
Screenshot 2023-04-07 at 1 47 29 PM

PR updated with this change!

**Review by gobengo — APPROVED** [review]
Looks great, and I'm glad we are making this super clear.

**Pull request merged**
